# Generated by Django 2.1.7 on 2019-03-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('duration', models.IntegerField(default=2)),
                ('budget', models.IntegerField(default=500)),
                ('noOfPeople', models.IntegerField(default=1)),
                ('skillLevel', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('windSpeed', models.IntegerField()),
                ('windDirection', models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West')], max_length=2)),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
