# Generated by Django 2.1.4 on 2018-12-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_auto_20181207_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='datePosted',
        ),
    ]
