# Generated by Django 2.1.4 on 2018-12-07 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0006_review_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2018, 12, 7, 21, 9, 2, 16101, tzinfo=utc)),
        ),
    ]
