# Generated by Django 2.1.4 on 2018-12-07 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_auto_20181207_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2018, 12, 7, 21, 10, 20, 597012, tzinfo=utc)),
        ),
    ]
