# Generated by Django 2.1.4 on 2018-12-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0008_auto_20181207_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
