# Generated by Django 2.1.7 on 2019-03-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_auto_20181207_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='datePosted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewText',
        ),
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='review',
            name='budget',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='review',
            name='duration',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='review',
            name='noOfPeople',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='skillLevel',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='review',
            name='temperature',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='review',
            name='windDirection',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='review',
            name='windSpeed',
            field=models.IntegerField(default=10),
        ),
    ]
